<?php
namespace AppBundle\Repository;

use AppBundle\Entity\Folder;
use Doctrine\ORM\EntityManager;
use \Doctrine\ORM\EntityRepository;

/**
 * FolderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FolderRepository extends EntityRepository
{
    public function save(Folder $folder)
    {
        /** @var EntityManager $em */
        $em = $this->getEntityManager();
        $em->persist($folder);
        $em->flush($folder);
    }
}
