<?php
namespace AppBundle\Repository;

use AppBundle\Entity\Photo;
use Doctrine\ORM\EntityManager;
use \Doctrine\ORM\EntityRepository;

/**
 * PhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoRepository extends EntityRepository
{
    public function save(Photo $photo)
    {
        /** @var EntityManager $em */
        $em = $this->getEntityManager();
        $em->persist($photo);
        $em->flush($photo);
    }

    public function delete(Photo $photo)
    {
        /** @var EntityManager $em */
        $em = $this->getEntityManager();
        $em->remove($photo);
        $em->flush($photo);
    }
}
